server:
  port: 8899 # web应用服务端口
  servlet:
    context-path: /kimgao
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 工作任务线程池，默认为io-threads的8倍
    worker-threads: 32

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wyh?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false # 启用缓存:建议生产开启
    check-template-location: true # 检查模版是否存在
    enabled: true # 是否启用
    encoding: UTF-8 # 模版编码
    excluded-view-names: # 应该从解析中排除的视图名称列表（用逗号分隔）
    mode: HTML5 # 模版模式
    prefix: classpath:/templates/ # 模版存放路径
    suffix: .html # 模版后缀

context:
  listener:
    classes: com.kimgao.bootlauch.customlistener.MyListener3

#mybatis:
#  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.kimgao.bootlauch: debug